namespace ServerHelper
{
    partial class Checker
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Checker));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.guna2BorderlessForm1 = new Guna.UI2.WinForms.Guna2BorderlessForm(this.components);
            this.nicktext = new Guna.UI2.WinForms.Guna2HtmlLabel();
            this.guna2Panel1 = new Guna.UI2.WinForms.Guna2Panel();
            this.guna2Panel2 = new Guna.UI2.WinForms.Guna2Panel();
            this.sidtext = new Guna.UI2.WinForms.Guna2HtmlLabel();
            this.guna2Panel3 = new Guna.UI2.WinForms.Guna2Panel();
            this.dstext = new Guna.UI2.WinForms.Guna2HtmlLabel();
            this.guna2PictureBox1 = new Guna.UI2.WinForms.Guna2PictureBox();
            this.exit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BunifuLabel1337 = new Bunifu.UI.WinForms.BunifuLabel();
            this.loadingtext = new Bunifu.UI.WinForms.BunifuLabel();
            this.Recent = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.GMOD = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.usb = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ph = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.recuva = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.LastActivity = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Everything = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.chromium = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.browser = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.guna2Button4 = new Guna.UI2.WinForms.Guna2Button();
            this.guna2Button5 = new Guna.UI2.WinForms.Guna2Button();
            this.guna2Button6 = new Guna.UI2.WinForms.Guna2Button();
            this.guna2Panel1.SuspendLayout();
            this.guna2Panel2.SuspendLayout();
            this.guna2Panel3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.guna2PictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // guna2BorderlessForm1
            // 
            this.guna2BorderlessForm1.BorderRadius = 10;
            this.guna2BorderlessForm1.ContainerControl = this;
            this.guna2BorderlessForm1.DockIndicatorTransparencyValue = 0.6D;
            this.guna2BorderlessForm1.ResizeForm = false;
            this.guna2BorderlessForm1.TransparentWhileDrag = true;
            // 
            // nicktext
            // 
            this.nicktext.BackColor = System.Drawing.Color.Transparent;
            this.nicktext.Font = new System.Drawing.Font("Consolas", 12F, System.Drawing.FontStyle.Bold);
            this.nicktext.ForeColor = System.Drawing.Color.White;
            this.nicktext.Location = new System.Drawing.Point(12, 8);
            this.nicktext.Name = "nicktext";
            this.nicktext.Size = new System.Drawing.Size(120, 21);
            this.nicktext.TabIndex = 23;
            this.nicktext.Text = "Nickname: ...";
            // 
            // guna2Panel1
            // 
            this.guna2Panel1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.guna2Panel1.BorderRadius = 10;
            this.guna2Panel1.BorderThickness = 2;
            this.guna2Panel1.Controls.Add(this.nicktext);
            this.guna2Panel1.Location = new System.Drawing.Point(331, 82);
            this.guna2Panel1.Name = "guna2Panel1";
            this.guna2Panel1.Size = new System.Drawing.Size(329, 38);
            this.guna2Panel1.TabIndex = 24;
            // 
            // guna2Panel2
            // 
            this.guna2Panel2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.guna2Panel2.BorderRadius = 10;
            this.guna2Panel2.BorderThickness = 2;
            this.guna2Panel2.Controls.Add(this.sidtext);
            this.guna2Panel2.Location = new System.Drawing.Point(331, 169);
            this.guna2Panel2.Name = "guna2Panel2";
            this.guna2Panel2.Size = new System.Drawing.Size(329, 38);
            this.guna2Panel2.TabIndex = 25;
            // 
            // sidtext
            // 
            this.sidtext.BackColor = System.Drawing.Color.Transparent;
            this.sidtext.Font = new System.Drawing.Font("Consolas", 12F, System.Drawing.FontStyle.Bold);
            this.sidtext.ForeColor = System.Drawing.Color.White;
            this.sidtext.Location = new System.Drawing.Point(12, 8);
            this.sidtext.Name = "sidtext";
            this.sidtext.Size = new System.Drawing.Size(111, 21);
            this.sidtext.TabIndex = 23;
            this.sidtext.Text = "SteamID: ...";
            // 
            // guna2Panel3
            // 
            this.guna2Panel3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.guna2Panel3.BorderRadius = 10;
            this.guna2Panel3.BorderThickness = 2;
            this.guna2Panel3.Controls.Add(this.dstext);
            this.guna2Panel3.Location = new System.Drawing.Point(331, 126);
            this.guna2Panel3.Name = "guna2Panel3";
            this.guna2Panel3.Size = new System.Drawing.Size(329, 38);
            this.guna2Panel3.TabIndex = 26;
            // 
            // dstext
            // 
            this.dstext.BackColor = System.Drawing.Color.Transparent;
            this.dstext.Font = new System.Drawing.Font("Consolas", 12F, System.Drawing.FontStyle.Bold);
            this.dstext.ForeColor = System.Drawing.Color.White;
            this.dstext.Location = new System.Drawing.Point(12, 8);
            this.dstext.Name = "dstext";
            this.dstext.Size = new System.Drawing.Size(111, 21);
            this.dstext.TabIndex = 23;
            this.dstext.Text = "Discord: ...";
            // 
            // guna2PictureBox1
            // 
            this.guna2PictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("guna2PictureBox1.Image")));
            this.guna2PictureBox1.ImageRotate = 0F;
            this.guna2PictureBox1.Location = new System.Drawing.Point(15, 17);
            this.guna2PictureBox1.Name = "guna2PictureBox1";
            this.guna2PictureBox1.Size = new System.Drawing.Size(18, 38);
            this.guna2PictureBox1.TabIndex = 18;
            this.guna2PictureBox1.TabStop = false;
            // 
            // exit
            // 
            this.exit.AllowAnimations = true;
            this.exit.AllowMouseEffects = true;
            this.exit.AllowToggling = false;
            this.exit.AnimationSpeed = 200;
            this.exit.AutoGenerateColors = false;
            this.exit.AutoRoundBorders = false;
            this.exit.AutoSizeLeftIcon = true;
            this.exit.AutoSizeRightIcon = true;
            this.exit.BackColor = System.Drawing.Color.Transparent;
            this.exit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.exit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("exit.BackgroundImage")));
            this.exit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.exit.ButtonText = "Закончить проверку";
            this.exit.ButtonTextMarginLeft = 0;
            this.exit.ColorContrastOnClick = 45;
            this.exit.ColorContrastOnHover = 45;
            this.exit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.exit.CustomizableEdges = borderEdges10;
            this.exit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.exit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.exit.DisabledFillColor = System.Drawing.Color.Empty;
            this.exit.DisabledForecolor = System.Drawing.Color.Empty;
            this.exit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.exit.Font = new System.Drawing.Font("Cascadia Code SemiBold", 9F, System.Drawing.FontStyle.Bold);
            this.exit.ForeColor = System.Drawing.Color.White;
            this.exit.IconLeft = null;
            this.exit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.exit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.exit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.exit.IconMarginLeft = 11;
            this.exit.IconPadding = 10;
            this.exit.IconRight = null;
            this.exit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.exit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.exit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.exit.IconSize = 25;
            this.exit.IdleBorderColor = System.Drawing.Color.Empty;
            this.exit.IdleBorderRadius = 0;
            this.exit.IdleBorderThickness = 0;
            this.exit.IdleFillColor = System.Drawing.Color.Empty;
            this.exit.IdleIconLeftImage = null;
            this.exit.IdleIconRightImage = null;
            this.exit.IndicateFocus = false;
            this.exit.Location = new System.Drawing.Point(508, 234);
            this.exit.Name = "exit";
            this.exit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.exit.OnDisabledState.BorderRadius = 15;
            this.exit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.exit.OnDisabledState.BorderThickness = 1;
            this.exit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(20)))), ((int)(((byte)(20)))));
            this.exit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(20)))), ((int)(((byte)(20)))));
            this.exit.OnDisabledState.IconLeftImage = null;
            this.exit.OnDisabledState.IconRightImage = null;
            this.exit.onHoverState.BorderColor = System.Drawing.Color.DarkRed;
            this.exit.onHoverState.BorderRadius = 15;
            this.exit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.exit.onHoverState.BorderThickness = 1;
            this.exit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(19)))), ((int)(((byte)(19)))), ((int)(((byte)(19)))));
            this.exit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.exit.onHoverState.IconLeftImage = null;
            this.exit.onHoverState.IconRightImage = null;
            this.exit.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.exit.OnIdleState.BorderRadius = 15;
            this.exit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.exit.OnIdleState.BorderThickness = 1;
            this.exit.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(25)))));
            this.exit.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.exit.OnIdleState.IconLeftImage = null;
            this.exit.OnIdleState.IconRightImage = null;
            this.exit.OnPressedState.BorderColor = System.Drawing.Color.Red;
            this.exit.OnPressedState.BorderRadius = 15;
            this.exit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.exit.OnPressedState.BorderThickness = 1;
            this.exit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(20)))), ((int)(((byte)(20)))));
            this.exit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.exit.OnPressedState.IconLeftImage = null;
            this.exit.OnPressedState.IconRightImage = null;
            this.exit.Size = new System.Drawing.Size(152, 30);
            this.exit.TabIndex = 44;
            this.exit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.exit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.exit.TextMarginLeft = 0;
            this.exit.TextPadding = new System.Windows.Forms.Padding(0);
            this.exit.UseDefaultRadiusAndThickness = true;
            this.exit.Click += new System.EventHandler(this.exit_Click_1);
            // 
            // BunifuLabel1337
            // 
            this.BunifuLabel1337.AllowParentOverrides = false;
            this.BunifuLabel1337.AutoEllipsis = false;
            this.BunifuLabel1337.CursorType = null;
            this.BunifuLabel1337.EllipsisFormat = Bunifu.UI.WinForms.Helpers.Ellipsis.EllipsisFormat.End;
            this.BunifuLabel1337.Font = new System.Drawing.Font("Cascadia Code SemiBold", 9F, System.Drawing.FontStyle.Bold);
            this.BunifuLabel1337.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(65)))), ((int)(((byte)(65)))), ((int)(((byte)(65)))));
            this.BunifuLabel1337.Location = new System.Drawing.Point(39, 34);
            this.BunifuLabel1337.Name = "BunifuLabel1337";
            this.BunifuLabel1337.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.BunifuLabel1337.Size = new System.Drawing.Size(119, 16);
            this.BunifuLabel1337.TabIndex = 43;
            this.BunifuLabel1337.Text = "Проверка на читы.";
            this.BunifuLabel1337.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.BunifuLabel1337.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // loadingtext
            // 
            this.loadingtext.AllowParentOverrides = false;
            this.loadingtext.AutoEllipsis = false;
            this.loadingtext.Cursor = System.Windows.Forms.Cursors.Default;
            this.loadingtext.CursorType = System.Windows.Forms.Cursors.Default;
            this.loadingtext.EllipsisFormat = Bunifu.UI.WinForms.Helpers.Ellipsis.EllipsisFormat.End;
            this.loadingtext.Font = new System.Drawing.Font("Cascadia Code SemiBold", 13F, System.Drawing.FontStyle.Bold);
            this.loadingtext.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(188)))), ((int)(((byte)(188)))), ((int)(((byte)(188)))));
            this.loadingtext.Location = new System.Drawing.Point(39, 12);
            this.loadingtext.Name = "loadingtext";
            this.loadingtext.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.loadingtext.Size = new System.Drawing.Size(140, 22);
            this.loadingtext.TabIndex = 42;
            this.loadingtext.Text = "IndianaChecker";
            this.loadingtext.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.loadingtext.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Recent
            // 
            this.Recent.AllowAnimations = true;
            this.Recent.AllowMouseEffects = true;
            this.Recent.AllowToggling = false;
            this.Recent.AnimationSpeed = 200;
            this.Recent.AutoGenerateColors = false;
            this.Recent.AutoRoundBorders = false;
            this.Recent.AutoSizeLeftIcon = true;
            this.Recent.AutoSizeRightIcon = true;
            this.Recent.BackColor = System.Drawing.Color.Transparent;
            this.Recent.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.Recent.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Recent.BackgroundImage")));
            this.Recent.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Recent.ButtonText = "Recent + Disk";
            this.Recent.ButtonTextMarginLeft = 0;
            this.Recent.ColorContrastOnClick = 45;
            this.Recent.ColorContrastOnHover = 45;
            this.Recent.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.Recent.CustomizableEdges = borderEdges9;
            this.Recent.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Recent.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Recent.DisabledFillColor = System.Drawing.Color.Empty;
            this.Recent.DisabledForecolor = System.Drawing.Color.Empty;
            this.Recent.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Recent.Font = new System.Drawing.Font("Cascadia Code SemiBold", 9F, System.Drawing.FontStyle.Bold);
            this.Recent.ForeColor = System.Drawing.Color.White;
            this.Recent.IconLeft = null;
            this.Recent.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Recent.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Recent.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Recent.IconMarginLeft = 11;
            this.Recent.IconPadding = 10;
            this.Recent.IconRight = null;
            this.Recent.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Recent.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Recent.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Recent.IconSize = 25;
            this.Recent.IdleBorderColor = System.Drawing.Color.Empty;
            this.Recent.IdleBorderRadius = 0;
            this.Recent.IdleBorderThickness = 0;
            this.Recent.IdleFillColor = System.Drawing.Color.Empty;
            this.Recent.IdleIconLeftImage = null;
            this.Recent.IdleIconRightImage = null;
            this.Recent.IndicateFocus = false;
            this.Recent.Location = new System.Drawing.Point(15, 75);
            this.Recent.Name = "Recent";
            this.Recent.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.Recent.OnDisabledState.BorderRadius = 15;
            this.Recent.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Recent.OnDisabledState.BorderThickness = 1;
            this.Recent.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(20)))), ((int)(((byte)(20)))));
            this.Recent.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(20)))), ((int)(((byte)(20)))));
            this.Recent.OnDisabledState.IconLeftImage = null;
            this.Recent.OnDisabledState.IconRightImage = null;
            this.Recent.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.Recent.onHoverState.BorderRadius = 15;
            this.Recent.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Recent.onHoverState.BorderThickness = 1;
            this.Recent.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.Recent.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Recent.onHoverState.IconLeftImage = null;
            this.Recent.onHoverState.IconRightImage = null;
            this.Recent.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.Recent.OnIdleState.BorderRadius = 15;
            this.Recent.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Recent.OnIdleState.BorderThickness = 1;
            this.Recent.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(25)))));
            this.Recent.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Recent.OnIdleState.IconLeftImage = null;
            this.Recent.OnIdleState.IconRightImage = null;
            this.Recent.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.Recent.OnPressedState.BorderRadius = 15;
            this.Recent.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Recent.OnPressedState.BorderThickness = 1;
            this.Recent.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.Recent.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Recent.OnPressedState.IconLeftImage = null;
            this.Recent.OnPressedState.IconRightImage = null;
            this.Recent.Size = new System.Drawing.Size(152, 30);
            this.Recent.TabIndex = 45;
            this.Recent.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Recent.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Recent.TextMarginLeft = 0;
            this.Recent.TextPadding = new System.Windows.Forms.Padding(0);
            this.Recent.UseDefaultRadiusAndThickness = true;
            this.Recent.Click += new System.EventHandler(this.Recent_Click);
            // 
            // GMOD
            // 
            this.GMOD.AllowAnimations = true;
            this.GMOD.AllowMouseEffects = true;
            this.GMOD.AllowToggling = false;
            this.GMOD.AnimationSpeed = 200;
            this.GMOD.AutoGenerateColors = false;
            this.GMOD.AutoRoundBorders = false;
            this.GMOD.AutoSizeLeftIcon = true;
            this.GMOD.AutoSizeRightIcon = true;
            this.GMOD.BackColor = System.Drawing.Color.Transparent;
            this.GMOD.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.GMOD.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("GMOD.BackgroundImage")));
            this.GMOD.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.GMOD.ButtonText = "[GMOD] Lua";
            this.GMOD.ButtonTextMarginLeft = 0;
            this.GMOD.ColorContrastOnClick = 45;
            this.GMOD.ColorContrastOnHover = 45;
            this.GMOD.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.GMOD.CustomizableEdges = borderEdges8;
            this.GMOD.DialogResult = System.Windows.Forms.DialogResult.None;
            this.GMOD.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.GMOD.DisabledFillColor = System.Drawing.Color.Empty;
            this.GMOD.DisabledForecolor = System.Drawing.Color.Empty;
            this.GMOD.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.GMOD.Font = new System.Drawing.Font("Cascadia Code SemiBold", 9F, System.Drawing.FontStyle.Bold);
            this.GMOD.ForeColor = System.Drawing.Color.White;
            this.GMOD.IconLeft = null;
            this.GMOD.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.GMOD.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.GMOD.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.GMOD.IconMarginLeft = 11;
            this.GMOD.IconPadding = 10;
            this.GMOD.IconRight = null;
            this.GMOD.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.GMOD.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.GMOD.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.GMOD.IconSize = 25;
            this.GMOD.IdleBorderColor = System.Drawing.Color.Empty;
            this.GMOD.IdleBorderRadius = 0;
            this.GMOD.IdleBorderThickness = 0;
            this.GMOD.IdleFillColor = System.Drawing.Color.Empty;
            this.GMOD.IdleIconLeftImage = null;
            this.GMOD.IdleIconRightImage = null;
            this.GMOD.IndicateFocus = false;
            this.GMOD.Location = new System.Drawing.Point(173, 75);
            this.GMOD.Name = "GMOD";
            this.GMOD.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.GMOD.OnDisabledState.BorderRadius = 15;
            this.GMOD.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.GMOD.OnDisabledState.BorderThickness = 1;
            this.GMOD.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(20)))), ((int)(((byte)(20)))));
            this.GMOD.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(20)))), ((int)(((byte)(20)))));
            this.GMOD.OnDisabledState.IconLeftImage = null;
            this.GMOD.OnDisabledState.IconRightImage = null;
            this.GMOD.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.GMOD.onHoverState.BorderRadius = 15;
            this.GMOD.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.GMOD.onHoverState.BorderThickness = 1;
            this.GMOD.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.GMOD.onHoverState.ForeColor = System.Drawing.Color.White;
            this.GMOD.onHoverState.IconLeftImage = null;
            this.GMOD.onHoverState.IconRightImage = null;
            this.GMOD.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.GMOD.OnIdleState.BorderRadius = 15;
            this.GMOD.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.GMOD.OnIdleState.BorderThickness = 1;
            this.GMOD.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(25)))));
            this.GMOD.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.GMOD.OnIdleState.IconLeftImage = null;
            this.GMOD.OnIdleState.IconRightImage = null;
            this.GMOD.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.GMOD.OnPressedState.BorderRadius = 15;
            this.GMOD.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.GMOD.OnPressedState.BorderThickness = 1;
            this.GMOD.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.GMOD.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.GMOD.OnPressedState.IconLeftImage = null;
            this.GMOD.OnPressedState.IconRightImage = null;
            this.GMOD.Size = new System.Drawing.Size(152, 30);
            this.GMOD.TabIndex = 46;
            this.GMOD.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.GMOD.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.GMOD.TextMarginLeft = 0;
            this.GMOD.TextPadding = new System.Windows.Forms.Padding(0);
            this.GMOD.UseDefaultRadiusAndThickness = true;
            this.GMOD.Click += new System.EventHandler(this.GMOD_Click);
            // 
            // usb
            // 
            this.usb.AllowAnimations = true;
            this.usb.AllowMouseEffects = true;
            this.usb.AllowToggling = false;
            this.usb.AnimationSpeed = 200;
            this.usb.AutoGenerateColors = false;
            this.usb.AutoRoundBorders = false;
            this.usb.AutoSizeLeftIcon = true;
            this.usb.AutoSizeRightIcon = true;
            this.usb.BackColor = System.Drawing.Color.Transparent;
            this.usb.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.usb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("usb.BackgroundImage")));
            this.usb.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.usb.ButtonText = "USBDeview";
            this.usb.ButtonTextMarginLeft = 0;
            this.usb.ColorContrastOnClick = 45;
            this.usb.ColorContrastOnHover = 45;
            this.usb.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.usb.CustomizableEdges = borderEdges7;
            this.usb.DialogResult = System.Windows.Forms.DialogResult.None;
            this.usb.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.usb.DisabledFillColor = System.Drawing.Color.Empty;
            this.usb.DisabledForecolor = System.Drawing.Color.Empty;
            this.usb.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.usb.Font = new System.Drawing.Font("Cascadia Code SemiBold", 9F, System.Drawing.FontStyle.Bold);
            this.usb.ForeColor = System.Drawing.Color.White;
            this.usb.IconLeft = null;
            this.usb.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.usb.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.usb.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.usb.IconMarginLeft = 11;
            this.usb.IconPadding = 10;
            this.usb.IconRight = null;
            this.usb.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.usb.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.usb.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.usb.IconSize = 25;
            this.usb.IdleBorderColor = System.Drawing.Color.Empty;
            this.usb.IdleBorderRadius = 0;
            this.usb.IdleBorderThickness = 0;
            this.usb.IdleFillColor = System.Drawing.Color.Empty;
            this.usb.IdleIconLeftImage = null;
            this.usb.IdleIconRightImage = null;
            this.usb.IndicateFocus = false;
            this.usb.Location = new System.Drawing.Point(15, 111);
            this.usb.Name = "usb";
            this.usb.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.usb.OnDisabledState.BorderRadius = 15;
            this.usb.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.usb.OnDisabledState.BorderThickness = 1;
            this.usb.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(20)))), ((int)(((byte)(20)))));
            this.usb.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(20)))), ((int)(((byte)(20)))));
            this.usb.OnDisabledState.IconLeftImage = null;
            this.usb.OnDisabledState.IconRightImage = null;
            this.usb.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.usb.onHoverState.BorderRadius = 15;
            this.usb.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.usb.onHoverState.BorderThickness = 1;
            this.usb.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.usb.onHoverState.ForeColor = System.Drawing.Color.White;
            this.usb.onHoverState.IconLeftImage = null;
            this.usb.onHoverState.IconRightImage = null;
            this.usb.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.usb.OnIdleState.BorderRadius = 15;
            this.usb.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.usb.OnIdleState.BorderThickness = 1;
            this.usb.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(25)))));
            this.usb.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.usb.OnIdleState.IconLeftImage = null;
            this.usb.OnIdleState.IconRightImage = null;
            this.usb.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.usb.OnPressedState.BorderRadius = 15;
            this.usb.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.usb.OnPressedState.BorderThickness = 1;
            this.usb.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.usb.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.usb.OnPressedState.IconLeftImage = null;
            this.usb.OnPressedState.IconRightImage = null;
            this.usb.Size = new System.Drawing.Size(152, 30);
            this.usb.TabIndex = 47;
            this.usb.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.usb.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.usb.TextMarginLeft = 0;
            this.usb.TextPadding = new System.Windows.Forms.Padding(0);
            this.usb.UseDefaultRadiusAndThickness = true;
            this.usb.Click += new System.EventHandler(this.usb_Click);
            // 
            // ph
            // 
            this.ph.AllowAnimations = true;
            this.ph.AllowMouseEffects = true;
            this.ph.AllowToggling = false;
            this.ph.AnimationSpeed = 200;
            this.ph.AutoGenerateColors = false;
            this.ph.AutoRoundBorders = false;
            this.ph.AutoSizeLeftIcon = true;
            this.ph.AutoSizeRightIcon = true;
            this.ph.BackColor = System.Drawing.Color.Transparent;
            this.ph.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.ph.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ph.BackgroundImage")));
            this.ph.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ph.ButtonText = "Process Hacker 2";
            this.ph.ButtonTextMarginLeft = 0;
            this.ph.ColorContrastOnClick = 45;
            this.ph.ColorContrastOnHover = 45;
            this.ph.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.ph.CustomizableEdges = borderEdges6;
            this.ph.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ph.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ph.DisabledFillColor = System.Drawing.Color.Empty;
            this.ph.DisabledForecolor = System.Drawing.Color.Empty;
            this.ph.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ph.Font = new System.Drawing.Font("Cascadia Code SemiBold", 9F, System.Drawing.FontStyle.Bold);
            this.ph.ForeColor = System.Drawing.Color.White;
            this.ph.IconLeft = null;
            this.ph.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ph.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ph.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ph.IconMarginLeft = 11;
            this.ph.IconPadding = 10;
            this.ph.IconRight = null;
            this.ph.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ph.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ph.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ph.IconSize = 25;
            this.ph.IdleBorderColor = System.Drawing.Color.Empty;
            this.ph.IdleBorderRadius = 0;
            this.ph.IdleBorderThickness = 0;
            this.ph.IdleFillColor = System.Drawing.Color.Empty;
            this.ph.IdleIconLeftImage = null;
            this.ph.IdleIconRightImage = null;
            this.ph.IndicateFocus = false;
            this.ph.Location = new System.Drawing.Point(173, 111);
            this.ph.Name = "ph";
            this.ph.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.ph.OnDisabledState.BorderRadius = 15;
            this.ph.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ph.OnDisabledState.BorderThickness = 1;
            this.ph.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(20)))), ((int)(((byte)(20)))));
            this.ph.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(20)))), ((int)(((byte)(20)))));
            this.ph.OnDisabledState.IconLeftImage = null;
            this.ph.OnDisabledState.IconRightImage = null;
            this.ph.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.ph.onHoverState.BorderRadius = 15;
            this.ph.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ph.onHoverState.BorderThickness = 1;
            this.ph.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.ph.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ph.onHoverState.IconLeftImage = null;
            this.ph.onHoverState.IconRightImage = null;
            this.ph.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.ph.OnIdleState.BorderRadius = 15;
            this.ph.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ph.OnIdleState.BorderThickness = 1;
            this.ph.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(25)))));
            this.ph.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.ph.OnIdleState.IconLeftImage = null;
            this.ph.OnIdleState.IconRightImage = null;
            this.ph.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.ph.OnPressedState.BorderRadius = 15;
            this.ph.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ph.OnPressedState.BorderThickness = 1;
            this.ph.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.ph.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ph.OnPressedState.IconLeftImage = null;
            this.ph.OnPressedState.IconRightImage = null;
            this.ph.Size = new System.Drawing.Size(152, 30);
            this.ph.TabIndex = 48;
            this.ph.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ph.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ph.TextMarginLeft = 0;
            this.ph.TextPadding = new System.Windows.Forms.Padding(0);
            this.ph.UseDefaultRadiusAndThickness = true;
            this.ph.Click += new System.EventHandler(this.ph_Click);
            // 
            // recuva
            // 
            this.recuva.AllowAnimations = true;
            this.recuva.AllowMouseEffects = true;
            this.recuva.AllowToggling = false;
            this.recuva.AnimationSpeed = 200;
            this.recuva.AutoGenerateColors = false;
            this.recuva.AutoRoundBorders = false;
            this.recuva.AutoSizeLeftIcon = true;
            this.recuva.AutoSizeRightIcon = true;
            this.recuva.BackColor = System.Drawing.Color.Transparent;
            this.recuva.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.recuva.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("recuva.BackgroundImage")));
            this.recuva.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.recuva.ButtonText = "Recuva";
            this.recuva.ButtonTextMarginLeft = 0;
            this.recuva.ColorContrastOnClick = 45;
            this.recuva.ColorContrastOnHover = 45;
            this.recuva.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.recuva.CustomizableEdges = borderEdges5;
            this.recuva.DialogResult = System.Windows.Forms.DialogResult.None;
            this.recuva.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.recuva.DisabledFillColor = System.Drawing.Color.Empty;
            this.recuva.DisabledForecolor = System.Drawing.Color.Empty;
            this.recuva.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.recuva.Font = new System.Drawing.Font("Cascadia Code SemiBold", 9F, System.Drawing.FontStyle.Bold);
            this.recuva.ForeColor = System.Drawing.Color.White;
            this.recuva.IconLeft = null;
            this.recuva.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.recuva.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.recuva.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.recuva.IconMarginLeft = 11;
            this.recuva.IconPadding = 10;
            this.recuva.IconRight = null;
            this.recuva.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.recuva.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.recuva.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.recuva.IconSize = 25;
            this.recuva.IdleBorderColor = System.Drawing.Color.Empty;
            this.recuva.IdleBorderRadius = 0;
            this.recuva.IdleBorderThickness = 0;
            this.recuva.IdleFillColor = System.Drawing.Color.Empty;
            this.recuva.IdleIconLeftImage = null;
            this.recuva.IdleIconRightImage = null;
            this.recuva.IndicateFocus = false;
            this.recuva.Location = new System.Drawing.Point(15, 147);
            this.recuva.Name = "recuva";
            this.recuva.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.recuva.OnDisabledState.BorderRadius = 15;
            this.recuva.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.recuva.OnDisabledState.BorderThickness = 1;
            this.recuva.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(20)))), ((int)(((byte)(20)))));
            this.recuva.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(20)))), ((int)(((byte)(20)))));
            this.recuva.OnDisabledState.IconLeftImage = null;
            this.recuva.OnDisabledState.IconRightImage = null;
            this.recuva.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.recuva.onHoverState.BorderRadius = 15;
            this.recuva.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.recuva.onHoverState.BorderThickness = 1;
            this.recuva.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.recuva.onHoverState.ForeColor = System.Drawing.Color.White;
            this.recuva.onHoverState.IconLeftImage = null;
            this.recuva.onHoverState.IconRightImage = null;
            this.recuva.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.recuva.OnIdleState.BorderRadius = 15;
            this.recuva.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.recuva.OnIdleState.BorderThickness = 1;
            this.recuva.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(25)))));
            this.recuva.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.recuva.OnIdleState.IconLeftImage = null;
            this.recuva.OnIdleState.IconRightImage = null;
            this.recuva.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.recuva.OnPressedState.BorderRadius = 15;
            this.recuva.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.recuva.OnPressedState.BorderThickness = 1;
            this.recuva.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.recuva.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.recuva.OnPressedState.IconLeftImage = null;
            this.recuva.OnPressedState.IconRightImage = null;
            this.recuva.Size = new System.Drawing.Size(152, 30);
            this.recuva.TabIndex = 49;
            this.recuva.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.recuva.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.recuva.TextMarginLeft = 0;
            this.recuva.TextPadding = new System.Windows.Forms.Padding(0);
            this.recuva.UseDefaultRadiusAndThickness = true;
            this.recuva.Click += new System.EventHandler(this.recuva_Click);
            // 
            // LastActivity
            // 
            this.LastActivity.AllowAnimations = true;
            this.LastActivity.AllowMouseEffects = true;
            this.LastActivity.AllowToggling = false;
            this.LastActivity.AnimationSpeed = 200;
            this.LastActivity.AutoGenerateColors = false;
            this.LastActivity.AutoRoundBorders = false;
            this.LastActivity.AutoSizeLeftIcon = true;
            this.LastActivity.AutoSizeRightIcon = true;
            this.LastActivity.BackColor = System.Drawing.Color.Transparent;
            this.LastActivity.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.LastActivity.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("LastActivity.BackgroundImage")));
            this.LastActivity.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LastActivity.ButtonText = "LastActivity";
            this.LastActivity.ButtonTextMarginLeft = 0;
            this.LastActivity.ColorContrastOnClick = 45;
            this.LastActivity.ColorContrastOnHover = 45;
            this.LastActivity.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.LastActivity.CustomizableEdges = borderEdges4;
            this.LastActivity.DialogResult = System.Windows.Forms.DialogResult.None;
            this.LastActivity.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.LastActivity.DisabledFillColor = System.Drawing.Color.Empty;
            this.LastActivity.DisabledForecolor = System.Drawing.Color.Empty;
            this.LastActivity.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.LastActivity.Font = new System.Drawing.Font("Cascadia Code SemiBold", 9F, System.Drawing.FontStyle.Bold);
            this.LastActivity.ForeColor = System.Drawing.Color.White;
            this.LastActivity.IconLeft = null;
            this.LastActivity.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.LastActivity.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.LastActivity.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.LastActivity.IconMarginLeft = 11;
            this.LastActivity.IconPadding = 10;
            this.LastActivity.IconRight = null;
            this.LastActivity.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.LastActivity.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.LastActivity.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.LastActivity.IconSize = 25;
            this.LastActivity.IdleBorderColor = System.Drawing.Color.Empty;
            this.LastActivity.IdleBorderRadius = 0;
            this.LastActivity.IdleBorderThickness = 0;
            this.LastActivity.IdleFillColor = System.Drawing.Color.Empty;
            this.LastActivity.IdleIconLeftImage = null;
            this.LastActivity.IdleIconRightImage = null;
            this.LastActivity.IndicateFocus = false;
            this.LastActivity.Location = new System.Drawing.Point(173, 146);
            this.LastActivity.Name = "LastActivity";
            this.LastActivity.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.LastActivity.OnDisabledState.BorderRadius = 15;
            this.LastActivity.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LastActivity.OnDisabledState.BorderThickness = 1;
            this.LastActivity.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(20)))), ((int)(((byte)(20)))));
            this.LastActivity.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(20)))), ((int)(((byte)(20)))));
            this.LastActivity.OnDisabledState.IconLeftImage = null;
            this.LastActivity.OnDisabledState.IconRightImage = null;
            this.LastActivity.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.LastActivity.onHoverState.BorderRadius = 15;
            this.LastActivity.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LastActivity.onHoverState.BorderThickness = 1;
            this.LastActivity.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.LastActivity.onHoverState.ForeColor = System.Drawing.Color.White;
            this.LastActivity.onHoverState.IconLeftImage = null;
            this.LastActivity.onHoverState.IconRightImage = null;
            this.LastActivity.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.LastActivity.OnIdleState.BorderRadius = 15;
            this.LastActivity.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LastActivity.OnIdleState.BorderThickness = 1;
            this.LastActivity.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(25)))));
            this.LastActivity.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.LastActivity.OnIdleState.IconLeftImage = null;
            this.LastActivity.OnIdleState.IconRightImage = null;
            this.LastActivity.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.LastActivity.OnPressedState.BorderRadius = 15;
            this.LastActivity.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LastActivity.OnPressedState.BorderThickness = 1;
            this.LastActivity.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.LastActivity.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.LastActivity.OnPressedState.IconLeftImage = null;
            this.LastActivity.OnPressedState.IconRightImage = null;
            this.LastActivity.Size = new System.Drawing.Size(152, 30);
            this.LastActivity.TabIndex = 50;
            this.LastActivity.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LastActivity.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.LastActivity.TextMarginLeft = 0;
            this.LastActivity.TextPadding = new System.Windows.Forms.Padding(0);
            this.LastActivity.UseDefaultRadiusAndThickness = true;
            this.LastActivity.Click += new System.EventHandler(this.LastActivity_Click);
            // 
            // Everything
            // 
            this.Everything.AllowAnimations = true;
            this.Everything.AllowMouseEffects = true;
            this.Everything.AllowToggling = false;
            this.Everything.AnimationSpeed = 200;
            this.Everything.AutoGenerateColors = false;
            this.Everything.AutoRoundBorders = false;
            this.Everything.AutoSizeLeftIcon = true;
            this.Everything.AutoSizeRightIcon = true;
            this.Everything.BackColor = System.Drawing.Color.Transparent;
            this.Everything.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.Everything.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Everything.BackgroundImage")));
            this.Everything.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Everything.ButtonText = "Everything";
            this.Everything.ButtonTextMarginLeft = 0;
            this.Everything.ColorContrastOnClick = 45;
            this.Everything.ColorContrastOnHover = 45;
            this.Everything.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.Everything.CustomizableEdges = borderEdges3;
            this.Everything.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Everything.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Everything.DisabledFillColor = System.Drawing.Color.Empty;
            this.Everything.DisabledForecolor = System.Drawing.Color.Empty;
            this.Everything.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Everything.Font = new System.Drawing.Font("Cascadia Code SemiBold", 9F, System.Drawing.FontStyle.Bold);
            this.Everything.ForeColor = System.Drawing.Color.White;
            this.Everything.IconLeft = null;
            this.Everything.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Everything.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Everything.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Everything.IconMarginLeft = 11;
            this.Everything.IconPadding = 10;
            this.Everything.IconRight = null;
            this.Everything.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Everything.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Everything.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Everything.IconSize = 25;
            this.Everything.IdleBorderColor = System.Drawing.Color.Empty;
            this.Everything.IdleBorderRadius = 0;
            this.Everything.IdleBorderThickness = 0;
            this.Everything.IdleFillColor = System.Drawing.Color.Empty;
            this.Everything.IdleIconLeftImage = null;
            this.Everything.IdleIconRightImage = null;
            this.Everything.IndicateFocus = false;
            this.Everything.Location = new System.Drawing.Point(15, 183);
            this.Everything.Name = "Everything";
            this.Everything.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.Everything.OnDisabledState.BorderRadius = 15;
            this.Everything.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Everything.OnDisabledState.BorderThickness = 1;
            this.Everything.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(20)))), ((int)(((byte)(20)))));
            this.Everything.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(20)))), ((int)(((byte)(20)))));
            this.Everything.OnDisabledState.IconLeftImage = null;
            this.Everything.OnDisabledState.IconRightImage = null;
            this.Everything.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.Everything.onHoverState.BorderRadius = 15;
            this.Everything.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Everything.onHoverState.BorderThickness = 1;
            this.Everything.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.Everything.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Everything.onHoverState.IconLeftImage = null;
            this.Everything.onHoverState.IconRightImage = null;
            this.Everything.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.Everything.OnIdleState.BorderRadius = 15;
            this.Everything.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Everything.OnIdleState.BorderThickness = 1;
            this.Everything.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(25)))));
            this.Everything.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Everything.OnIdleState.IconLeftImage = null;
            this.Everything.OnIdleState.IconRightImage = null;
            this.Everything.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.Everything.OnPressedState.BorderRadius = 15;
            this.Everything.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Everything.OnPressedState.BorderThickness = 1;
            this.Everything.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.Everything.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Everything.OnPressedState.IconLeftImage = null;
            this.Everything.OnPressedState.IconRightImage = null;
            this.Everything.Size = new System.Drawing.Size(152, 30);
            this.Everything.TabIndex = 51;
            this.Everything.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Everything.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Everything.TextMarginLeft = 0;
            this.Everything.TextPadding = new System.Windows.Forms.Padding(0);
            this.Everything.UseDefaultRadiusAndThickness = true;
            this.Everything.Click += new System.EventHandler(this.Everything_Click);
            // 
            // chromium
            // 
            this.chromium.AllowAnimations = true;
            this.chromium.AllowMouseEffects = true;
            this.chromium.AllowToggling = false;
            this.chromium.AnimationSpeed = 200;
            this.chromium.AutoGenerateColors = false;
            this.chromium.AutoRoundBorders = false;
            this.chromium.AutoSizeLeftIcon = true;
            this.chromium.AutoSizeRightIcon = true;
            this.chromium.BackColor = System.Drawing.Color.Transparent;
            this.chromium.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.chromium.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("chromium.BackgroundImage")));
            this.chromium.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.chromium.ButtonText = "[GMOD] Chromium";
            this.chromium.ButtonTextMarginLeft = 0;
            this.chromium.ColorContrastOnClick = 45;
            this.chromium.ColorContrastOnHover = 45;
            this.chromium.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.chromium.CustomizableEdges = borderEdges2;
            this.chromium.DialogResult = System.Windows.Forms.DialogResult.None;
            this.chromium.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.chromium.DisabledFillColor = System.Drawing.Color.Empty;
            this.chromium.DisabledForecolor = System.Drawing.Color.Empty;
            this.chromium.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.chromium.Font = new System.Drawing.Font("Cascadia Code SemiBold", 9F, System.Drawing.FontStyle.Bold);
            this.chromium.ForeColor = System.Drawing.Color.White;
            this.chromium.IconLeft = null;
            this.chromium.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.chromium.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.chromium.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.chromium.IconMarginLeft = 11;
            this.chromium.IconPadding = 10;
            this.chromium.IconRight = null;
            this.chromium.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.chromium.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.chromium.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.chromium.IconSize = 25;
            this.chromium.IdleBorderColor = System.Drawing.Color.Empty;
            this.chromium.IdleBorderRadius = 0;
            this.chromium.IdleBorderThickness = 0;
            this.chromium.IdleFillColor = System.Drawing.Color.Empty;
            this.chromium.IdleIconLeftImage = null;
            this.chromium.IdleIconRightImage = null;
            this.chromium.IndicateFocus = false;
            this.chromium.Location = new System.Drawing.Point(173, 183);
            this.chromium.Name = "chromium";
            this.chromium.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.chromium.OnDisabledState.BorderRadius = 15;
            this.chromium.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.chromium.OnDisabledState.BorderThickness = 1;
            this.chromium.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(20)))), ((int)(((byte)(20)))));
            this.chromium.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(20)))), ((int)(((byte)(20)))));
            this.chromium.OnDisabledState.IconLeftImage = null;
            this.chromium.OnDisabledState.IconRightImage = null;
            this.chromium.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.chromium.onHoverState.BorderRadius = 15;
            this.chromium.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.chromium.onHoverState.BorderThickness = 1;
            this.chromium.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.chromium.onHoverState.ForeColor = System.Drawing.Color.White;
            this.chromium.onHoverState.IconLeftImage = null;
            this.chromium.onHoverState.IconRightImage = null;
            this.chromium.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.chromium.OnIdleState.BorderRadius = 15;
            this.chromium.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.chromium.OnIdleState.BorderThickness = 1;
            this.chromium.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(25)))));
            this.chromium.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.chromium.OnIdleState.IconLeftImage = null;
            this.chromium.OnIdleState.IconRightImage = null;
            this.chromium.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.chromium.OnPressedState.BorderRadius = 15;
            this.chromium.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.chromium.OnPressedState.BorderThickness = 1;
            this.chromium.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.chromium.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.chromium.OnPressedState.IconLeftImage = null;
            this.chromium.OnPressedState.IconRightImage = null;
            this.chromium.Size = new System.Drawing.Size(152, 30);
            this.chromium.TabIndex = 52;
            this.chromium.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.chromium.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.chromium.TextMarginLeft = 0;
            this.chromium.TextPadding = new System.Windows.Forms.Padding(0);
            this.chromium.UseDefaultRadiusAndThickness = true;
            this.chromium.Click += new System.EventHandler(this.chromium_Click);
            // 
            // browser
            // 
            this.browser.AllowAnimations = true;
            this.browser.AllowMouseEffects = true;
            this.browser.AllowToggling = false;
            this.browser.AnimationSpeed = 200;
            this.browser.AutoGenerateColors = false;
            this.browser.AutoRoundBorders = false;
            this.browser.AutoSizeLeftIcon = true;
            this.browser.AutoSizeRightIcon = true;
            this.browser.BackColor = System.Drawing.Color.Transparent;
            this.browser.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.browser.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("browser.BackgroundImage")));
            this.browser.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.browser.ButtonText = "Open browser";
            this.browser.ButtonTextMarginLeft = 0;
            this.browser.ColorContrastOnClick = 45;
            this.browser.ColorContrastOnHover = 45;
            this.browser.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.browser.CustomizableEdges = borderEdges1;
            this.browser.DialogResult = System.Windows.Forms.DialogResult.None;
            this.browser.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.browser.DisabledFillColor = System.Drawing.Color.Empty;
            this.browser.DisabledForecolor = System.Drawing.Color.Empty;
            this.browser.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.browser.Font = new System.Drawing.Font("Cascadia Code SemiBold", 9F, System.Drawing.FontStyle.Bold);
            this.browser.ForeColor = System.Drawing.Color.White;
            this.browser.IconLeft = null;
            this.browser.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.browser.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.browser.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.browser.IconMarginLeft = 11;
            this.browser.IconPadding = 10;
            this.browser.IconRight = null;
            this.browser.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.browser.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.browser.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.browser.IconSize = 25;
            this.browser.IdleBorderColor = System.Drawing.Color.Empty;
            this.browser.IdleBorderRadius = 0;
            this.browser.IdleBorderThickness = 0;
            this.browser.IdleFillColor = System.Drawing.Color.Empty;
            this.browser.IdleIconLeftImage = null;
            this.browser.IdleIconRightImage = null;
            this.browser.IndicateFocus = false;
            this.browser.Location = new System.Drawing.Point(94, 219);
            this.browser.Name = "browser";
            this.browser.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.browser.OnDisabledState.BorderRadius = 15;
            this.browser.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.browser.OnDisabledState.BorderThickness = 1;
            this.browser.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(20)))), ((int)(((byte)(20)))));
            this.browser.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(20)))), ((int)(((byte)(20)))));
            this.browser.OnDisabledState.IconLeftImage = null;
            this.browser.OnDisabledState.IconRightImage = null;
            this.browser.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.browser.onHoverState.BorderRadius = 15;
            this.browser.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.browser.onHoverState.BorderThickness = 1;
            this.browser.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.browser.onHoverState.ForeColor = System.Drawing.Color.White;
            this.browser.onHoverState.IconLeftImage = null;
            this.browser.onHoverState.IconRightImage = null;
            this.browser.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(40)))), ((int)(((byte)(40)))));
            this.browser.OnIdleState.BorderRadius = 15;
            this.browser.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.browser.OnIdleState.BorderThickness = 1;
            this.browser.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(25)))));
            this.browser.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.browser.OnIdleState.IconLeftImage = null;
            this.browser.OnIdleState.IconRightImage = null;
            this.browser.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.browser.OnPressedState.BorderRadius = 15;
            this.browser.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.browser.OnPressedState.BorderThickness = 1;
            this.browser.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(98)))), ((int)(((byte)(24)))), ((int)(((byte)(184)))));
            this.browser.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.browser.OnPressedState.IconLeftImage = null;
            this.browser.OnPressedState.IconRightImage = null;
            this.browser.Size = new System.Drawing.Size(152, 30);
            this.browser.TabIndex = 53;
            this.browser.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.browser.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.browser.TextMarginLeft = 0;
            this.browser.TextPadding = new System.Windows.Forms.Padding(0);
            this.browser.UseDefaultRadiusAndThickness = true;
            this.browser.Click += new System.EventHandler(this.browser_Click);
            // 
            // guna2Button4
            // 
            this.guna2Button4.Animated = true;
            this.guna2Button4.BackColor = System.Drawing.Color.Transparent;
            this.guna2Button4.BorderColor = System.Drawing.Color.Transparent;
            this.guna2Button4.BorderRadius = 8;
            this.guna2Button4.BorderThickness = 2;
            this.guna2Button4.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.guna2Button4.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.guna2Button4.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.guna2Button4.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.guna2Button4.FillColor = System.Drawing.Color.Transparent;
            this.guna2Button4.Font = new System.Drawing.Font("Segoe UI Semibold", 11.25F, System.Drawing.FontStyle.Bold);
            this.guna2Button4.ForeColor = System.Drawing.Color.Wheat;
            this.guna2Button4.HoverState.CustomBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(118)))), ((int)(((byte)(0)))), ((int)(((byte)(148)))));
            this.guna2Button4.Image = global::ServerHelper.Properties.Resources.ds;
            this.guna2Button4.Location = new System.Drawing.Point(582, 12);
            this.guna2Button4.Name = "guna2Button4";
            this.guna2Button4.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
            this.guna2Button4.Size = new System.Drawing.Size(22, 35);
            this.guna2Button4.TabIndex = 56;
            this.guna2Button4.Click += new System.EventHandler(this.guna2Button4_Click_1);
            // 
            // guna2Button5
            // 
            this.guna2Button5.Animated = true;
            this.guna2Button5.BackColor = System.Drawing.Color.Transparent;
            this.guna2Button5.BorderColor = System.Drawing.Color.Transparent;
            this.guna2Button5.BorderRadius = 8;
            this.guna2Button5.BorderThickness = 2;
            this.guna2Button5.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.guna2Button5.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.guna2Button5.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.guna2Button5.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.guna2Button5.FillColor = System.Drawing.Color.Transparent;
            this.guna2Button5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.25F, System.Drawing.FontStyle.Bold);
            this.guna2Button5.ForeColor = System.Drawing.Color.White;
            this.guna2Button5.HoverState.CustomBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(118)))), ((int)(((byte)(0)))), ((int)(((byte)(148)))));
            this.guna2Button5.Image = global::ServerHelper.Properties.Resources.vk;
            this.guna2Button5.Location = new System.Drawing.Point(610, 12);
            this.guna2Button5.Name = "guna2Button5";
            this.guna2Button5.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
            this.guna2Button5.Size = new System.Drawing.Size(22, 35);
            this.guna2Button5.TabIndex = 55;
            this.guna2Button5.Click += new System.EventHandler(this.guna2Button5_Click_1);
            // 
            // guna2Button6
            // 
            this.guna2Button6.Animated = true;
            this.guna2Button6.BackColor = System.Drawing.Color.Transparent;
            this.guna2Button6.BorderColor = System.Drawing.Color.Transparent;
            this.guna2Button6.BorderRadius = 8;
            this.guna2Button6.BorderThickness = 2;
            this.guna2Button6.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.guna2Button6.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.guna2Button6.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.guna2Button6.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.guna2Button6.FillColor = System.Drawing.Color.Transparent;
            this.guna2Button6.Font = new System.Drawing.Font("Segoe UI Semibold", 11.25F, System.Drawing.FontStyle.Bold);
            this.guna2Button6.ForeColor = System.Drawing.Color.White;
            this.guna2Button6.HoverState.CustomBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(118)))), ((int)(((byte)(0)))), ((int)(((byte)(148)))));
            this.guna2Button6.Image = global::ServerHelper.Properties.Resources.tg;
            this.guna2Button6.Location = new System.Drawing.Point(638, 12);
            this.guna2Button6.Name = "guna2Button6";
            this.guna2Button6.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(60)))), ((int)(((byte)(60)))));
            this.guna2Button6.Size = new System.Drawing.Size(22, 35);
            this.guna2Button6.TabIndex = 54;
            this.guna2Button6.Click += new System.EventHandler(this.guna2Button6_Click_1);
            // 
            // Checker
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(20)))), ((int)(((byte)(20)))), ((int)(((byte)(20)))));
            this.ClientSize = new System.Drawing.Size(672, 283);
            this.Controls.Add(this.guna2Button4);
            this.Controls.Add(this.guna2Button5);
            this.Controls.Add(this.guna2Button6);
            this.Controls.Add(this.browser);
            this.Controls.Add(this.chromium);
            this.Controls.Add(this.Everything);
            this.Controls.Add(this.LastActivity);
            this.Controls.Add(this.recuva);
            this.Controls.Add(this.ph);
            this.Controls.Add(this.usb);
            this.Controls.Add(this.GMOD);
            this.Controls.Add(this.Recent);
            this.Controls.Add(this.exit);
            this.Controls.Add(this.BunifuLabel1337);
            this.Controls.Add(this.loadingtext);
            this.Controls.Add(this.guna2Panel3);
            this.Controls.Add(this.guna2Panel2);
            this.Controls.Add(this.guna2Panel1);
            this.Controls.Add(this.guna2PictureBox1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "Checker";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "IndianaRP | Checker";
            this.guna2Panel1.ResumeLayout(false);
            this.guna2Panel1.PerformLayout();
            this.guna2Panel2.ResumeLayout(false);
            this.guna2Panel2.PerformLayout();
            this.guna2Panel3.ResumeLayout(false);
            this.guna2Panel3.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.guna2PictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Guna.UI2.WinForms.Guna2BorderlessForm guna2BorderlessForm1;
        private Guna.UI2.WinForms.Guna2PictureBox guna2PictureBox1;
        private Guna.UI2.WinForms.Guna2Panel guna2Panel2;
        private Guna.UI2.WinForms.Guna2Panel guna2Panel1;
        private Guna.UI2.WinForms.Guna2Panel guna2Panel3;
        public Guna.UI2.WinForms.Guna2HtmlLabel sidtext;
        public Guna.UI2.WinForms.Guna2HtmlLabel nicktext;
        public Guna.UI2.WinForms.Guna2HtmlLabel dstext;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton exit;
        private Bunifu.UI.WinForms.BunifuLabel BunifuLabel1337;
        private Bunifu.UI.WinForms.BunifuLabel loadingtext;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Recent;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton GMOD;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton usb;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ph;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton recuva;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton LastActivity;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Everything;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton chromium;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton browser;
        private Guna.UI2.WinForms.Guna2Button guna2Button4;
        private Guna.UI2.WinForms.Guna2Button guna2Button5;
        private Guna.UI2.WinForms.Guna2Button guna2Button6;
    }
}